language: python
python:
- 3.5
- 3.6
- 3.7-dev
- 3.8
services:
- rabbitmq
env:
- PYTHONASYNCIODEBUG=1
install:
- pip install -r requirements_dev.txt
- pip install --editable .
- pip freeze

addons:
  apt:
    packages:
      - rabbitmq-server
before_script: "sudo rabbitmq-plugins enable rabbitmq_management"
script: "make test && make pylint"
notifications:
  email: true
  irc:
    channels:
    - chat.freenode.net#aioamqp
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
  slack:
    secure: apz1q5tPlt/F/YMMbP/1n7DhlCgfl6TZPo+IY79lrj8ko51srq043OksWnrwiCPz0e8pXG4QPOBhnP/IkkupeH9qQ/JziN35Cn7tfCsY9Id0i35KDe6gJPZKJd9+w9fF1d+ceYMyyN86JIpyuKCta0DP2FV+wwdAmP5TJv+kh6E=
